version: "3.9"
services:
  blog:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8001:80"
    volumes:
      - blog_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: learn
      WORDPRESS_DB_PASSWORD: learn@!
      WORDPRESS_DB_NAME: blogdb
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogdb
      MYSQL_USER: learn
      MYSQL_PASSWORD: learn@!
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
volumes:
  db_data:
  blog_data:
