version: "3.8"
services:
  app:
    build:
      context: ./website
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "5001:5000"
    restart: always
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  redis-data:

